from .campo import Campo

ALIASES_CLI: dict[str, str] = {
    "frequencias": "auditar_frequencias",
    "f": "auditar_frequencias",
    "relatorios": "auditar_relatorios",
    "r": "auditar_relatorios",
    "ra": "auditar_relatorios",
    "rc": "compilacao_de_relatorios",
    "softskills": "auditar_softskills",
    "s": "auditar_softskills",
    "torpedo": "torpedo_de_forum",
    "t": "torpedo_de_forum",
}

ESQUEMAS: dict[str, list[Campo]] = {
    "auditar_frequencias": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="env",
            descricao="Login de acesso ao Moodle",
            env_var="MOODLE_USUARIO",
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="env",
            descricao="Senha de acesso ao Moodle",
            env_var="MOODLE_SENHA",
        ),
        Campo(
            chave="moodle_url_login",
            rotulo="URL de login do Moodle",
            tipo="url",
            origem="settings",
            descricao="Página de login do Moodle (ex: https://moodle.inst.edu/login/index.php)",
            json_chaves=["moodle", "urlLogin"],
        ),
        Campo(
            chave="moodle_urls_frequencias",
            rotulo="URLs de frequências por turma",
            tipo="dict_str_url",
            origem="settings",
            descricao="Mapeamento de nome da turma → URL da frequência no Moodle",
            json_chaves=["moodle", "urlsFrequencias"],
        ),
        Campo(
            chave="moodle_caminho_exportacao",
            rotulo="Caminho de exportação das frequências",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os arquivos XLSX de frequência serão salvos",
            json_chaves=["moodle", "caminhoExportacao"],
        ),
        Campo(
            chave="gsheets_id_planilha",
            rotulo="ID da planilha Google Sheets",
            tipo="texto",
            origem="settings",
            descricao="ID da planilha de destino no Google Sheets",
            json_chaves=["gsheets", "idPlanilha"],
        ),
    ],
    "auditar_relatorios": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="env",
            env_var="MOODLE_USUARIO",
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="env",
            env_var="MOODLE_SENHA",
        ),
        Campo(
            chave="moodle_url_login",
            rotulo="URL de login do Moodle",
            tipo="url",
            origem="settings",
            json_chaves=["moodle", "urlLogin"],
        ),
        Campo(
            chave="moodle_urls_relatorios",
            rotulo="URLs dos relatórios",
            tipo="lista_url",
            origem="settings",
            descricao="Lista de URLs das páginas de feedback do Moodle",
            json_chaves=["moodle", "urlsRelatorios"],
        ),
        Campo(
            chave="moodle_headless",
            rotulo="Modo headless do navegador",
            tipo="bool",
            origem="settings",
            descricao="Se verdadeiro, o navegador roda em segundo plano sem interface gráfica (padrão: sim)",
            obrigatorio=False,
            json_chaves=["moodle", "headless"],
        ),
        Campo(
            chave="moodle_exportar_analise",
            rotulo="Exportar análise dos relatórios",
            tipo="bool",
            origem="settings",
            descricao="Se verdadeiro, exporta o resultado da análise para um arquivo local (padrão: não)",
            obrigatorio=False,
            json_chaves=["moodle", "exportarAnaliseRelatorio"],
        ),
        Campo(
            chave="moodle_caminho_exportacao_analise",
            rotulo="Caminho de exportação da análise",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde o CSV de análise será salvo (opcional)",
            obrigatorio=False,
            json_chaves=["moodle", "caminhoExportacaoAnalise"],
            depende_de="moodle_exportar_analise",
        ),
        Campo(
            chave="moodle_csv_residentes",
            rotulo="CSV de residentes",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para o arquivo CSV com a lista de residentes",
            json_chaves=["moodle", "csvResidentes"],
        ),
        Campo(
            chave="gsheets_id_planilha",
            rotulo="ID da planilha Google Sheets",
            tipo="texto",
            origem="settings",
            json_chaves=["gsheets", "idPlanilha"],
        ),
        Campo(
            chave="gsheets_nome_aba",
            rotulo="Nome da aba na planilha",
            tipo="texto",
            origem="settings",
            json_chaves=["gsheets", "nomeAba"],
        ),
        Campo(
            chave="gsheets_caminho_backup",
            rotulo="Caminho de backup local",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde o backup XLSX da planilha será salvo",
            json_chaves=["gsheets", "caminhoBackupLocal"],
        ),
    ],
    "auditar_softskills": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="env",
            env_var="MOODLE_USUARIO",
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="env",
            env_var="MOODLE_SENHA",
        ),
        Campo(
            chave="moodle_url",
            rotulo="URL base do Moodle",
            tipo="url",
            origem="settings",
            descricao="URL raiz do Moodle sem path (ex: https://moodle.inst.edu)",
            json_chaves=["moodle", "url"],
        ),
        Campo(
            chave="moodle_bootcamp_cat_id",
            rotulo="ID da categoria bootcamp no Moodle",
            tipo="texto",
            origem="settings",
            descricao="ID da categoria de cursos do bootcamp",
            json_chaves=["moodle", "bootcampCatId"],
        ),
        Campo(
            chave="moodle_aprovados_cat_id",
            rotulo="ID da categoria de aprovados no Moodle",
            tipo="texto",
            origem="settings",
            descricao="ID da categoria de cursos dos aprovados",
            json_chaves=["moodle", "aprovadosCatId"],
        ),
        Campo(
            chave="drive_folder_id",
            rotulo="ID da pasta no Google Drive",
            tipo="texto",
            origem="settings",
            descricao="ID da pasta de destino para upload no Google Drive",
            json_chaves=["drive", "folderId"],
        ),
        Campo(
            chave="drive_credentials_path",
            rotulo="Caminho das credenciais do Google",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para o arquivo credentials.json da conta de serviço",
            json_chaves=["drive", "credentialsPath"],
        ),
        Campo(
            chave="output_dir",
            rotulo="Diretório de saída do bootcamp",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os CSVs das turmas serão salvos (padrão: bootcamps)",
            json_chaves=["outputDir"],
        ),
        Campo(
            chave="aprovados_dir",
            rotulo="Diretório dos aprovados",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os CSVs dos aprovados serão salvos (padrão: aprovados)",
            json_chaves=["aprovadosDir"],
        ),
    ],
    "compilacao_de_relatorios": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="env",
            env_var="MOODLE_USUARIO",
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="env",
            env_var="MOODLE_SENHA",
        ),
        Campo(
            chave="moodle_url_login",
            rotulo="URL de login do Moodle",
            tipo="url",
            origem="settings",
            json_chaves=["moodle", "urlLogin"],
        ),
        Campo(
            chave="moodle_meses",
            rotulo="URLs dos relatórios por mês",
            tipo="dict_str_lista_url",
            origem="settings",
            descricao="Mapeamento de nome do mês → lista de URLs semanais de feedback",
            json_chaves=["moodle", "meses"],
        ),
        Campo(
            chave="headless",
            rotulo="Modo headless do navegador",
            tipo="bool",
            origem="settings",
            descricao="Se verdadeiro, o navegador roda em segundo plano sem interface gráfica",
            json_chaves=["headless"],
        ),
        Campo(
            chave="pdf_caminho_saida",
            rotulo="Caminho de saída dos PDFs",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os PDFs compilados serão salvos",
            json_chaves=["pdf", "caminhoSaida"],
        ),
        Campo(
            chave="pdf_csv_residentes",
            rotulo="CSV de residentes",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para o arquivo CSV com a lista de residentes/alunos",
            json_chaves=["pdf", "csvResidentes"],
        ),
    ],
    "torpedo_de_forum": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="env",
            env_var="MOODLE_USUARIO",
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="env",
            env_var="MOODLE_SENHA",
        ),
        Campo(
            chave="moodle_url_login",
            rotulo="URL de login do Moodle",
            tipo="url",
            origem="settings",
            json_chaves=["moodle", "urlLogin"],
        ),
        Campo(
            chave="moodle_urls_foruns",
            rotulo="URLs dos fóruns",
            tipo="lista_url",
            origem="settings",
            descricao="Lista de URLs dos fóruns onde a postagem será feita",
            json_chaves=["moodle", "urlsForuns"],
        ),
        Campo(
            chave="moodle_headless",
            rotulo="Modo headless do navegador",
            tipo="bool",
            origem="settings",
            descricao="Se verdadeiro, o navegador roda em segundo plano",
            json_chaves=["moodle", "headless"],
        ),
        Campo(
            chave="moodle_post_delay",
            rotulo="Intervalo entre posts (segundos)",
            tipo="int",
            origem="settings",
            descricao="Tempo de espera em segundos entre cada postagem em fórum",
            json_chaves=["moodle", "postDelay"],
        ),
        Campo(
            chave="moodle_caminho_post_file",
            rotulo="Arquivo markdown da postagem",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para o arquivo .md com o conteúdo da postagem",
            json_chaves=["moodle", "caminhoPostFile"],
        ),
        Campo(
            chave="moodle_caminho_imagem",
            rotulo="Imagem anexa (opcional)",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para imagem a ser anexada à postagem (deixe vazio para nenhuma)",
            obrigatorio=False,
            json_chaves=["moodle", "caminhoImagem"],
        ),
    ],
}
