from .campo import Campo

ALIASES_CLI: dict[str, str] = {
    "frequencias": "frequencias",
    "f": "frequencias",
    "relatorios": "relatorios",
    "r": "relatorios",
    "softskills": "softskills",
    "s": "softskills",
    "torpedo": "torpedo",
    "t": "torpedo",
}

ESQUEMAS: dict[str, list[Campo]] = {
    "frequencias": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="settings",
            descricao="Login de acesso ao Moodle",
            settings_chaves=["moodle", "usuario"],
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="keyring",
            descricao="Senha de acesso ao Moodle (armazenada no keyring do sistema operacional)",
        ),
        Campo(
            chave="moodle_url_login",
            rotulo="URL de login do Moodle",
            tipo="url",
            origem="settings",
            descricao="Página de login do Moodle (ex: https://moodle.inst.edu/login/index.php)",
            settings_chaves=["moodle", "urlLogin"],
        ),
        Campo(
            chave="moodle_urls_frequencias",
            rotulo="URLs de frequências por turma",
            tipo="dict_str_url",
            origem="settings",
            descricao="Mapeamento de nome da turma → URL da frequência no Moodle",
            settings_chaves=["moodle", "urlsFrequencias"],
        ),
        Campo(
            chave="moodle_caminho_exportacao",
            rotulo="Caminho de exportação das frequências",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os arquivos XLSX de frequência serão salvos",
            settings_chaves=["moodle", "caminhoExportacao"],
            scripts=("auditar", "extrair"),
        ),
        Campo(
            chave="gsheets_id_planilha",
            rotulo="ID da planilha Google Sheets",
            tipo="texto",
            origem="settings",
            descricao="ID da planilha de destino no Google Sheets",
            settings_chaves=["gsheets", "idPlanilha"],
            scripts=("auditar",),
        ),
        Campo(
            chave="gsheets_caminho_json_credenciais",
            rotulo="Caminho do credentials.json",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para o arquivo credentials.json da conta de serviço Google",
            settings_chaves=["gsheets", "caminhoJsonCredenciais"],
            caminho_absoluto=True,
            scripts=("auditar",),
        ),
        Campo(
            chave="atas_caminho_saida",
            rotulo="Caminho de saída das atas em PDF",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde as atas de frequência (PDF) serão salvas",
            settings_chaves=["atas", "caminhoSaida"],
            scripts=("compilar",),
        ),
        Campo(
            chave="atas_caminho_logo",
            rotulo="Logo do programa (opcional)",
            tipo="caminho",
            origem="settings",
            descricao="Imagem exibida no topo da capa da ata (deixe vazio para nenhuma)",
            obrigatorio=False,
            settings_chaves=["atas", "caminhoLogo"],
            scripts=("compilar",),
        ),
        Campo(
            chave="atas_caminho_assinatura",
            rotulo="Assinatura de logos da Aponti (opcional)",
            tipo="caminho",
            origem="settings",
            descricao="Imagem exibida no rodapé da capa da ata (deixe vazio para nenhuma)",
            obrigatorio=False,
            settings_chaves=["atas", "caminhoAssinatura"],
            scripts=("compilar",),
        ),
    ],
    "relatorios": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="settings",
            settings_chaves=["moodle", "usuario"],
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="keyring",
        ),
        Campo(
            chave="moodle_url_login",
            rotulo="URL de login do Moodle",
            tipo="url",
            origem="settings",
            settings_chaves=["moodle", "urlLogin"],
        ),
        Campo(
            chave="moodle_urls_relatorios",
            rotulo="URLs dos relatórios",
            tipo="lista_url",
            origem="settings",
            descricao="Lista de URLs das páginas de feedback do Moodle",
            settings_chaves=["moodle", "urlsRelatorios"],
            scripts=("extrair",),
        ),
        Campo(
            chave="moodle_caminho_download_relatorio",
            rotulo="Caminho de download dos relatórios",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os CSVs baixados do Moodle serão salvos",
            settings_chaves=["moodle", "caminhoDownloadRelatorio"],
            scripts=("extrair",),
        ),
        Campo(
            chave="moodle_meses",
            rotulo="URLs dos relatórios por mês",
            tipo="dict_str_lista_url",
            origem="settings",
            descricao="Mapeamento de nome do mês → lista de URLs semanais de feedback",
            settings_chaves=["moodle", "meses"],
            scripts=("compilar",),
        ),
        Campo(
            chave="pdf_caminho_saida",
            rotulo="Caminho de saída dos PDFs",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os PDFs compilados serão salvos",
            settings_chaves=["pdf", "caminhoSaida"],
            scripts=("compilar",),
        ),
    ],
    "softskills": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="settings",
            settings_chaves=["moodle", "usuario"],
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="keyring",
        ),
        Campo(
            chave="moodle_url",
            rotulo="URL base do Moodle",
            tipo="url",
            origem="settings",
            descricao="URL raiz do Moodle sem path (ex: https://moodle.inst.edu)",
            settings_chaves=["moodle", "urlBase"],
        ),
        Campo(
            chave="moodle_bootcamp_cat_id",
            rotulo="ID da categoria bootcamp no Moodle",
            tipo="texto",
            origem="settings",
            descricao="ID da categoria de cursos do bootcamp",
            settings_chaves=["moodle", "bootcampCatId"],
        ),
        Campo(
            chave="moodle_aprovados_cat_id",
            rotulo="ID da categoria de aprovados no Moodle",
            tipo="texto",
            origem="settings",
            descricao="ID da categoria de cursos dos aprovados",
            settings_chaves=["moodle", "aprovadosCatId"],
        ),
        Campo(
            chave="drive_folder_id",
            rotulo="ID da pasta no Google Drive",
            tipo="texto",
            origem="settings",
            descricao="ID da pasta de destino para upload no Google Drive",
            settings_chaves=["drive", "folderId"],
        ),
        Campo(
            chave="drive_credentials_path",
            rotulo="Caminho das credenciais do Google",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para o arquivo credentials.json da conta de serviço",
            settings_chaves=["drive", "credentialsPath"],
        ),
        Campo(
            chave="output_dir",
            rotulo="Diretório de saída do bootcamp",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os CSVs das turmas serão salvos (padrão: bootcamps)",
            settings_chaves=["outputDir"],
        ),
        Campo(
            chave="aprovados_dir",
            rotulo="Diretório dos aprovados",
            tipo="caminho",
            origem="settings",
            descricao="Diretório onde os CSVs dos aprovados serão salvos (padrão: aprovados)",
            settings_chaves=["aprovadosDir"],
        ),
    ],
    "torpedo": [
        Campo(
            chave="moodle_usuario",
            rotulo="Usuário do Moodle",
            tipo="texto",
            origem="settings",
            settings_chaves=["moodle", "usuario"],
        ),
        Campo(
            chave="moodle_senha",
            rotulo="Senha do Moodle",
            tipo="senha",
            origem="keyring",
        ),
        Campo(
            chave="moodle_url_login",
            rotulo="URL de login do Moodle",
            tipo="url",
            origem="settings",
            settings_chaves=["moodle", "urlLogin"],
        ),
        Campo(
            chave="moodle_urls_foruns",
            rotulo="URLs dos fóruns",
            tipo="lista_url",
            origem="settings",
            descricao="Lista de URLs dos fóruns onde a postagem será feita",
            settings_chaves=["moodle", "urlsForuns"],
        ),
        Campo(
            chave="moodle_headless",
            rotulo="Modo headless do navegador",
            tipo="bool",
            origem="settings",
            descricao="Se verdadeiro, o navegador roda em segundo plano",
            settings_chaves=["moodle", "headless"],
        ),
        Campo(
            chave="moodle_post_delay",
            rotulo="Intervalo entre posts (segundos)",
            tipo="int",
            origem="settings",
            descricao="Tempo de espera em segundos entre cada postagem em fórum",
            settings_chaves=["moodle", "postDelay"],
        ),
        Campo(
            chave="moodle_caminho_post_file",
            rotulo="Arquivo markdown da postagem",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para o arquivo .md com o conteúdo da postagem",
            settings_chaves=["moodle", "caminhoPostFile"],
        ),
        Campo(
            chave="moodle_caminho_imagem",
            rotulo="Imagem anexa (opcional)",
            tipo="caminho",
            origem="settings",
            descricao="Caminho para imagem a ser anexada à postagem (deixe vazio para nenhuma)",
            obrigatorio=False,
            settings_chaves=["moodle", "caminhoImagem"],
        ),
    ],
}
